### ISSUE TITLE
DU Czechitas: Zoo

### ISSUE THREAD

**Issue by zu-pribylova** [zu-pribylova/du_zoo_czechitas#1]
@akunzova

**Comment by akunzova** [comment]
Ahoj:) Kod je moc pekne strukturovany, citelny. Komentare u funkcí/metod jsou napomocne, super navyk. 

Jinak me napadlo jeste pridat treba upper() u tech inicialu, abychom meli jistotu ze budou velkym pismenem, ale to je jen drobnost.

Dávám splněno ✔️
